import type { Video } from '@/types';

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'dQw4w9WgXcQ',
    title: 'Claude 4 Just Changed Everything — Here\'s What It Can Do',
    description: 'Anthropic released Claude 4 and it beats GPT-4o on every benchmark. Here\'s what that means for developers.',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    publishedAt: new Date(Date.now() - 2 * 3600_000).toISOString(),
    category: 'ai-tech',
    platform: 'youtube',
    viewCount: 142000,
    duration: '0:58',
    tags: ['AI', 'Claude', 'Anthropic'],
  },
  {
    id: 'ScMzIvxBSi4',
    title: 'Startup Raises $50M in 48 Hours — The AI Business Story of 2026',
    description: 'A two-person AI startup just closed a $50M seed round. Here\'s how they did it.',
    thumbnail: 'https://img.youtube.com/vi/ScMzIvxBSi4/hqdefault.jpg',
    publishedAt: new Date(Date.now() - 5 * 3600_000).toISOString(),
    category: 'business',
    platform: 'youtube',
    viewCount: 89000,
    duration: '0:55',
    tags: ['Startup', 'Funding', 'AI Business'],
  },
  {
    id: 'oHg5SJYRHA0',
    title: 'NASA Found Water on Mars — What This Really Means',
    description: 'NASA\'s Perseverance rover confirmed liquid water traces under the Martian surface. Here\'s the science.',
    thumbnail: 'https://img.youtube.com/vi/oHg5SJYRHA0/hqdefault.jpg',
    publishedAt: new Date(Date.now() - 8 * 3600_000).toISOString(),
    category: 'science',
    platform: 'youtube',
    viewCount: 310000,
    duration: '0:52',
    tags: ['NASA', 'Mars', 'Science'],
  },
  {
    id: 'eBGIQ7ZuuiU',
    title: 'X Algorithm Change Is Silencing Millions of Accounts',
    description: 'X\'s latest algorithm update is drastically reducing reach for accounts under 1,000 followers.',
    thumbnail: 'https://img.youtube.com/vi/eBGIQ7ZuuiU/hqdefault.jpg',
    publishedAt: new Date(Date.now() - 12 * 3600_000).toISOString(),
    category: 'social',
    platform: 'youtube',
    viewCount: 55000,
    duration: '0:47',
    tags: ['X', 'Twitter', 'Social Media'],
  },
  {
    id: 'M7lc1UVf-VE',
    title: 'This Robot Can Now Perform Surgery Better Than Doctors',
    description: 'A new AI-powered surgical robot achieved 99.7% accuracy in a clinical trial — beating human surgeons.',
    thumbnail: 'https://img.youtube.com/vi/M7lc1UVf-VE/hqdefault.jpg',
    publishedAt: new Date(Date.now() - 18 * 3600_000).toISOString(),
    category: 'innovation',
    platform: 'youtube',
    viewCount: 220000,
    duration: '0:59',
    tags: ['Robotics', 'AI', 'Healthcare'],
  },
  {
    id: 'tntOCGkgt98',
    title: 'India Becomes 3rd Largest Economy — What Changed',
    description: 'India officially overtook Japan to become the world\'s 3rd largest economy in 2026.',
    thumbnail: 'https://img.youtube.com/vi/tntOCGkgt98/hqdefault.jpg',
    publishedAt: new Date(Date.now() - 24 * 3600_000).toISOString(),
    category: 'world',
    platform: 'youtube',
    viewCount: 198000,
    duration: '0:54',
    tags: ['India', 'Economy', 'World'],
  },
];
